echo "[INFO] Special characters for paths . and .."
echo "[INFO] . is the current directory."
echo "[INFO] .. is the parent directory above you in the filesystem."
echo "[INFO] Changing directories works with either absolute, relative, or canonical paths."
echo "$ cd /absolute/path/to/file"
echo -e "$ cd relative/path/to/file\n"
echo "[INFO] Go back to your /home folder"
echo "$ cd ~"
echo "$ cd"
