#!/bin/bash
# read-secret: input a secret passphrase

# -t adds a count down timer
# -s doesn't display what the user types
# -p display a prompt for the user
if read -t 10 -sp "Enter secret passphrase > " secret_pass; then
	echo -e "\nSecret passphrase = '$secret_pass'"
else
	echo -e "\nInput timed out" >&2
	exit 1
fi
