#!/bin/bash

# Number of seconds to display the results
DELAY=5

while [[ "$REPLY" != 0 ]]; do
	clear
	cat <<- _EOF_
	Please Select:

	1. Display System Information
	2. Display Disk & Memory Space
	3. Display Home Space Utilisation
	0. Quit
_EOF_
	read -p "Enter selection [0-3] > "

	if [[ "$REPLY" =~ ^[0-3]$ ]]; then
		if [[ "$REPLY" == 1 ]]; then
			echo "Hostname:	$HOSTNAME."
			lsb_release -a
			uptime
			sleep "$DELAY"
		fi
		if [[ "$REPLY" == 2 ]]; then
			df -h
			free -h
			sleep "$DELAY"
		fi
		if [[ "$REPLY" == 3 ]]; then
			if [[ "$(id -u)" -eq 0 ]]; then
				echo "Home Space Utilisation (All Users)"
				du -sh /home/*
			else
				echo "Home Space Utilisation ($USER)"
				du -sh "$HOME"
			fi
			sleep "$DELAY"
		fi
	else
		echo "Invalid entry." >&2
		sleep "$DELAY"
	fi
done
echo "Program terminated."


