#!/bin/bash

file_info() {
	if [[ -e "$1" ]]; then
		echo -e "\nFile type: "
		file "$1"
		echo -e "\nFile status: "
		stat "$1"
		return 0
	else
		echo "$FUNCNAME: usage: $FUNCNAME file" >&2
		return 1
	fi
}

# Pass the file_info function a parameter.
file_info "file_info_function"
