#!/bin/bash
# read-integer: evaluate the value of an integer.

# echo -n supresses the trailing \n
echo -n "Please enter an integer -> "
# read the users input into a variable
read int
# check if the variable is a positive or negative number
if [[ "$int" =~ ^-?[0-9]+$ ]]; then
	# if it is a number, check what type of number
	if [ "$int" -eq 0 ]; then
		echo "$int is zero."
	else
		if [ "$int" -lt 0 ]; then
			echo "$int is negative."
		else
			echo "$int is positive."
		fi
		if [ $((int % 2)) -eq 0 ]; then
			echo "$int is even."
		else
			echo "$int is odd."	
		fi
	fi
# error out because input was not a number
else
	echo "Input value is not an integer." >&2
	exit 1
fi
