#!/bin/bash

# Update the IFS (internal field separator) which by default is ' ' \t and \n

# stores information about users and groups.
FILE=/etc/passwd
read -p "Enter a username > " user_name

# use command substitution to run a command
file_info="$(grep "^$user_name:" $FILE)"

# check if the string length is > 0 
if [ -n "$file_info" ]; then
	# change the IFS character
	# read all the values into multiple variables
	# <<< is a here string, which is like a here document only shorter (a single line).
	# the reason the here string is used because | doesn't work with read
	IFS=":" read user pw uid gid name home shell <<< "$file_info"
	echo "User = '$user'"
	echo "UID = '$uid'"
	echo "GID = '$gid'"
	echo "Full Name = '$name'"
	echo "Home Dir. = '$home'"
	echo "Shell = '$shell'"
else
	echo "User '$user_name' not found." >&2
	exit 1
fi
