#!/bin/bash
# Program to output system information.

# global variables
TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

# functions
report_uptime () {
	cat <<- _EOF_
		<h2>System Uptime</h2>
		<pre>$(uptime)</pre>
		_EOF_
	return
}

report_disk_space () {
	cat <<- _EOF_
		<h2>Disk Space Utilisation</h2>
		<pre>$(df -h)</pre>
		_EOF_
	return
}

report_home_space () {
	if [[ "$(id -u)" -eq 0 ]]; then
		cat <<- _EOF_
			<h2>Home Space Utilisation (All Users)</h2>
			<pre>$(du -sh /home/*)</pre>
			_EOF_
	else
		cat <<- _EOF_
			<h2>Home Space Utilisation ($USER)</h2>
			<pre>$(du -sh $HOME)</pre>
			_EOF_
	fi
	return
}

# heredoc syntax
cat << _EOF_
<!doctype html>
<html>
<head>
	<title>Report</title>
</head>
<body>
	<h1>$TITLE</h1>
	<p>$TIMESTAMP</p>
	$(report_uptime)
	$(report_disk_space)
	$(report_home_space)
</body>
</html>
_EOF_
