#!/bin/bash

# read into multiple variables 1 line at a time from the piped output of sort
# 0 status is returned while lines are read, non-0 status returned at EOF which ends the loop
# -k 1,1 sort on column 1 using the first character
# -k 2n sort on column 2 using numeric sorting
sort -k 1,1 -k 2n distros.txt | while read distro version release; do
	printf "Distro: %s\tVersion: %s\tReleased: %s\n" \
	"$distro" \
	"$version" \
	"$release" 
done
