#!/bin/bash
cat <<- _OUTPUT_
[INFO] This is the code being executed.
foo=
echo ${foo:-"This is the value if foo is unset."}
echo $foo

[INFO] This is the output of the code being executed.
_OUTPUT_

foo=
echo ${foo:-"This is the value if foo is unset."}
echo $foo

cat <<- _OUTPUT_
[INFO] This is the code being executed.
foo=bar
echo ${foo:-"This is the value if foo is unset."}
echo $foo

[INFO] This is the output of the code being executed.
_OUTPUT_

foo=bar
echo ${foo:-"This is the value if foo is unset."}
echo $foo


