#!/bin/bash
# Program to output system information.

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

echo "<!doctype html>
<html>
<head>
	<title>Report</title>
</head>
<body>
	<h1>$TITLE</h1>
	<p>$TIMESTAMP</p>
</body>
</html>"
