#!/bin/bash

# Validates a user's input in a variety of ways.

# create a function
invalid_input () {
	echo "'$REPLY' is invalid input" >&2
	exit 1
}

# p displays a prompt on the same line
# read without a variable stores into $REPLY
read -p "Enter an item > "

# check the input
# if the string is empty
[[ -z "$REPLY" ]] && invalid_input

# if the string has more than one word
(( "$(echo "$REPLY" | wc -w)" > 1 )) && invalid_input

# check for recommended valid filenames
# =~ checks the string against regex
if [[ "$REPLY" =~ ^[-[:alnum:]\._]+$ ]]; then
	echo "'$REPLY' is a valid recommended filename."

	# check if the file exists
	if [[ -e "$REPLY" ]]; then
		echo "And the file named '$REPLY' exists."
	else
		echo "But the file named '$REPLY' doesn't exist."
	fi

	# check if floating point number
	if [[ "$REPLY" =~ ^-?[[:digit:]]*\.[[:digit:]]+$ ]]; then
		echo "'$REPLY' is a floating point number."
	else
		echo "'$REPLY' isn't a floating point number."
	fi

	# check if an integer
	if [[ "$REPLY" =~ ^-?[0-9]+$ ]]; then
		echo "'$REPLY' is an integer."
	else
		echo "'$REPLY' isn't an integer."
	fi
else
	echo "The string '$REPLY' is not a valid recommended filename. Use [0-9A-Za-z_\\-] only" 
fi
